apiVersion: v1
kind: Pod
metadata:
  name: tf
spec:
  nodeName: edgeblazer-desktop
  containers:
    - name: nvidia
      image: jitteam/jetson-nano-tf-gpu:latest
      command: [ "sleep" ]
      args: [ "1d" ]
